import {
  ArchiveRestore,
  Boxes,
  CalendarRange,
  Download,
  Image as ImageIcon,
  KeyRound,
  LayoutDashboard,
  PackagePlus,
  QrCode,
  RefreshCw,
  ScanLine,
  Printer,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  Signal,
  Sparkles,
  TriangleAlert,
  UserCircle2,
} from 'lucide-react';

import type { NavItem } from '../asset-ui/types';

export const navigation: NavItem[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    group: 'operations',
    hint: 'Tagesüberblick',
  },
  {
    key: 'planning',
    label: 'Einsatzplanung',
    icon: CalendarRange,
    group: 'operations',
    hint: 'Projektbedarf & Engpässe',
  },
  {
    key: 'inventory',
    label: 'Inventar',
    icon: Boxes,
    group: 'operations',
    hint: 'Assets & Verfügbarkeit',
  },
  {
    key: 'externalPool',
    label: 'Fremdbestand',
    icon: PackagePlus,
    group: 'operations',
    hint: 'Miet-, Leih- & Externgeräte',
  },
  {
    key: 'checkinCheckout',
    label: 'Ein-/Auslagerung',
    icon: ShieldCheck,
    group: 'operations',
    hint: 'Ausgabe & Rücknahme',
  },
  {
    key: 'tickets',
    label: 'Defekte / Tickets',
    icon: TriangleAlert,
    group: 'operations',
    hint: 'Schäden & Wartung',
  },
  {
    key: 'users',
    label: 'Benutzerverwaltung',
    icon: UserCircle2,
    group: 'administration',
    hint: 'Rollen & Team',
  },
  {
    key: 'categories',
    label: 'Kategorien',
    icon: Shapes,
    group: 'administration',
    hint: 'Stammdaten',
  },
  {
    key: 'importExport',
    label: 'Import / Export',
    icon: Download,
    group: 'administration',
    hint: 'Datenflüsse',
  },
  {
    key: 'backup',
    label: 'Backup',
    icon: ArchiveRestore,
    group: 'administration',
    hint: 'Sichern & Wiederherstellen',
  },
  {
    key: 'qrFunctions',
    label: 'QR-Code',
    icon: QrCode,
    group: 'administration',
    hint: 'Scanaktionen',
  },
  {
    key: 'massPrint',
    label: 'Massendruck',
    icon: Printer,
    group: 'administration',
    hint: 'QR-Labels drucken',
  },
  {
    key: 'labelAudit',
    label: 'Label-Prüfung',
    icon: ScanLine,
    group: 'administration',
    hint: 'QR-Labels nach Druck prüfen',
  },
  {
    key: 'updateNotes',
    label: 'Update-Notizen',
    icon: Sparkles,
    group: 'administration',
    hint: 'Versionshinweise pflegen',
  },
  {
    key: 'loginBackground',
    label: 'Login-Seite',
    icon: ImageIcon,
    group: 'administration',
    hint: 'Hintergrundbild verwalten',
  },
  {
    key: 'rolesPermissions',
    label: 'Rollen & Rechte',
    icon: KeyRound,
    group: 'administration',
    hint: 'Berechtigungen pflegen',
  },
  {
    key: 'securityLogs',
    label: 'Sicherheit & Protokolle',
    icon: ShieldAlert,
    group: 'administration',
    hint: 'Anmeldungen & Sicherheitsereignisse',
  },
  {
    key: 'telecomPass',
    label: 'Telekompass',
    icon: Signal,
    group: 'administration',
    hint: 'Preis pro Buchung',
  },
  {
    key: 'systemUpdate',
    label: 'Systemupdate',
    icon: RefreshCw,
    group: 'administration',
    hint: 'Neue Version einspielen',
  },
];
