import {
  ArchiveRestore,
  Boxes,
  CalendarRange,
  Download,
  KeyRound,
  LayoutDashboard,
  PackagePlus,
  QrCode,
  ScanLine,
  Printer,
  Shapes,
  ShieldCheck,
  Sparkles,
  TriangleAlert,
  UserCircle2,
} from 'lucide-react';

import type { NavItem } from '../asset-ui/types';

export const navigation: NavItem[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    group: 'operations',
    hint: 'Tagesüberblick',
  },
  {
    key: 'planning',
    label: 'Einsatzplanung',
    icon: CalendarRange,
    group: 'operations',
    hint: 'Projektbedarf & Engpässe',
  },
  {
    key: 'inventory',
    label: 'Inventar',
    icon: Boxes,
    group: 'operations',
    hint: 'Assets & Verfügbarkeit',
  },
  {
    key: 'externalPool',
    label: 'Fremdbestand',
    icon: PackagePlus,
    group: 'operations',
    hint: 'Miet-, Leih- & Externgeräte',
  },
  {
    key: 'checkinCheckout',
    label: 'Ein-/Auslagerung',
    icon: ShieldCheck,
    group: 'operations',
    hint: 'Ausgabe & Rücknahme',
  },
  {
    key: 'tickets',
    label: 'Defekte / Tickets',
    icon: TriangleAlert,
    group: 'operations',
    hint: 'Schäden & Wartung',
  },
  {
    key: 'users',
    label: 'Benutzerverwaltung',
    icon: UserCircle2,
    group: 'administration',
    hint: 'Rollen & Team',
  },
  {
    key: 'categories',
    label: 'Kategorien',
    icon: Shapes,
    group: 'administration',
    hint: 'Stammdaten',
  },
  {
    key: 'importExport',
    label: 'Import / Export',
    icon: Download,
    group: 'administration',
    hint: 'Datenflüsse',
  },
  {
    key: 'backup',
    label: 'Backup',
    icon: ArchiveRestore,
    group: 'administration',
    hint: 'Sichern & Wiederherstellen',
  },
  {
    key: 'qrFunctions',
    label: 'QR-Code',
    icon: QrCode,
    group: 'administration',
    hint: 'Scanaktionen',
  },
  {
    key: 'massPrint',
    label: 'Massendruck',
    icon: Printer,
    group: 'administration',
    hint: 'QR-Labels drucken',
  },
  {
    key: 'labelAudit',
    label: 'Label-Prüfung',
    icon: ScanLine,
    group: 'administration',
    hint: 'QR-Labels nach Druck prüfen',
  },
  {
    key: 'updateNotes',
    label: 'Update-Notizen',
    icon: Sparkles,
    group: 'administration',
    hint: 'Versionshinweise pflegen',
  },
  {
    key: 'rolesPermissions',
    label: 'Rollen & Rechte',
    icon: KeyRound,
    group: 'administration',
    hint: 'Berechtigungen pflegen',
  },
];
